api/urls.py
from django.urls import path
from api.views import UserListAPIView, ProductListAPIView, StatisticsListAPIView

app_name = 'api'
urlpatterns = [
    path('user_list/', UserListAPIView.as_view(), name='user_list'),
    path('user_list/<int:product_id>', ProductListAPIView.as_view()),
    path('statistics/', StatisticsListAPIView.as_view(), name='statistics')
]

my_test_app/urls.py
from django.urls import path
from my_test_app.views import MainView, UserLoginView, StatisticsView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView

app_name = 'my_test_app'
urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('login/', UserLoginView.as_view(), name='login' ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('statistics', StatisticsView.as_view(), name='statistics'),
]

test_hard_qode/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_test_app.urls', namespace='my_test_app')),
    path('api/', include('api.urls', namespace='api')),
]

my_test_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator


# Задание 1.2
class Lesson(models.Model):
    name = models.CharField(max_length=128, blank=False, null=False)
    url_address = models.URLField(blank=False, null=False)
    # Длина видео урока в секундах
    length_in_seconds = models.PositiveSmallIntegerField(default=0, blank=False, null=False)


# Моя модель пользователя
class User(AbstractUser):
    # Просмотры видео
    video_watches = models.ManyToManyField(
        to='Lesson',
        through="VideoWatch",
        blank=True,
    )


# Задание 1.1
class Product(models.Model):
    name = models.CharField(max_length=128)
    owner = models.ForeignKey(
        to='User',
        related_name='owner',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    lessons = models.ManyToManyField(
        to='Lesson',
        blank=True,
    )


# Доступы для пользователей из задания 1.1
class Accesses(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    accesses = models.ManyToManyField(to=Product, blank=True)


# Задание 1.3
class VideoWatch(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, blank=True, null=True)
    time_stop = models.FloatField(
        default=0.0,
        validators=[
            MaxValueValidator(1.0),
            MinValueValidator(0.0)
        ]
    )
    is_watched = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.time_stop >= 0.8:
            self.is_watched = True
        else:
            self.is_watched = False

        super().save(*args, **kwargs)

my_test_app/forms.py
# Форма для аутентификации пользователей
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from my_test_app.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя пользователя'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль'
    }))

    class Meta:
        model = User
        fields = ("username", 'password')

api/views.py
from rest_framework.generics import ListAPIView
from my_test_app.models import Accesses, Product
from api.serializers import ProductSerializer, ProductStatisticsSerializer
from rest_framework.permissions import IsAuthenticated


# Задание 2.1
class UserListAPIView(ListAPIView):
    serializer_class = ProductSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        accesses_to_products = Accesses.objects.filter(user=self.request.user).values('accesses')
        return Product.objects.filter(pk__in=accesses_to_products)


# Задание 2.2
class ProductListAPIView(ListAPIView):
    serializer_class = ProductSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        if Accesses.objects.filter(user=self.request.user, accesses=self.kwargs.get('product_id')):
            return Product.objects.filter(id=self.kwargs.get('product_id'))
        else:
            return None


# Задание 2.3
class StatisticsListAPIView(ListAPIView):
    serializer_class = ProductStatisticsSerializer

    def get_queryset(self):
        return Product.objects.all()

my_test_app/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView

from my_test_app.forms import UserLoginForm


class MainView(TemplateView):
    template_name = 'main.html'


class UserLoginView(LoginView):
    template_name = 'login.html'
    form_class = UserLoginForm


class StatisticsView(TemplateView):
    template_name = 'statistics.html'

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Test HardQode</title>
</head>
<body>

<!-- Head -->
<nav>
    <a href="{% url 'my_test_app:main' %}">Главная</a> |
    <a href="{% url 'api:statistics' %}">Общая статистика</a> |
    {% if user.is_authenticated %}
        <a>{{ user.username }}</a> |
        <a href="{% url 'api:user_list' %}">Мои продукты</a> |
        {% if user.is_superuser or user.is_staff %}
            <a href="{% url 'admin:index' %}">Админ-панель</a> |
        {% endif %}
        <a href="{%  url 'my_test_app:logout' %}">Выйти</a>
    {% else %}
        <a href="{% url 'my_test_app:login' %}">Войти</a> |
    {% endif %}
</nav>

<!-- Content -->
{% block content %}
{% endblock content %}

<!-- Footer -->
<nav id="footer">
    Мой <a href="http://github.com/heshegto" target="_blank">GitHub</a>
    |
    Моя почта: <a href="mailto:heshkin@gmail.com" target="_blank">heshkin@gmail.com</a>
</nav>
</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block content %}
        <h3>Авторизация</h3>
        <form action="{% url 'my_test_app:login' %}" method="post">
            {% csrf_token %}
            <div>
                <label for="{{ form.username.id_for_label }}">
                    Имя пользователя
                </label>
                {{ form.username }}
            </div>
            <div>
                <label for="{{ form.password.id_for_label }}">
                    Пароль
                </label>
                {{ form.password }}
            </div>
            <div>
                <input type="submit" value="Авторизоваться">
            </div>
        </form>
{% endblock %}

templates/main.html
{% extends 'base.html' %}

{% block content %}
    <p>Реализация заданий из раздела 1 видна в файле my_test_app/models.py</p>
    <p>Для просмотра заданий 2.1 и 2.2 нужно сначала войти в аккаунт (суперпользователь: "hesh", обычные пользователи:
        "user_2", "user_3"; для каждого пароль: "heshhesh")</p>
    <p>Чтобы увидеть задание 2.1 нужно после входа в аккаунт перейти к "Мои продукты"</p>
    <p>Чтобы увидеть задание 2.2 нужно после входа в аккаунт, после перехода к "Мои продукты" дописать в адресной строке
        id продукта (например: 127.0.0.1:8000/api/user_list/1)</p>
    <p>Для того, чтобы просмотреть выполненное задание 2.3, необходимо нажать на ссылку "Общая статистика"</p>
    <p>Реализация заданий из раздела 2 видна в разделе api в файлах serializer.py и views.py</p>
{% endblock %}

templates/statistics.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}